 <?php 
   include('fonction.php');


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method='get'>
    <input type='text' name='nom' >
    <input type='text' name='prenom' >
    <input type='text' name='id_cliens' >
    <button type='submit' name='action' value='historique'>historique</button><div><table>
</form>
</body>
</html>
